#!/usr/bin/env bash

mkdir -p ../dist
mkdir -p ./built

echo "bundle sharedb for testing ..."
./node_modules/.bin/lsc -cp --no-header src/sharedb.ls > built/_sharedb.js
./node_modules/.bin/browserify \
  built/_sharedb.js \
  -x ot-json0 \
  -g unassertify \
  -g envify \
  -g uglifyify \
  -t aliasify --global-transform aliasify \
  -s sharedb \
  -p browser-pack-flat/plugin \
  > ../dist/sharedb.js
./node_modules/.bin/uglifyjs ../dist/sharedb.js -m -c > ../dist/sharedb.min.js

rm -rf ./built
